name: Deploy Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git*' ./ ubuntu@13.201.190.2:/var/www/html
          ssh ubuntu@13.201.190.2 'sudo chown -R ubuntu:ubuntu /var/www/html'
