name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no ./ ubuntu@13.201.190.2:/var/www/html

    - name: SSH into EC2 and set up
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.201.190.2 << 'EOF'
          cd /var/www/html
          # Perform any setup tasks here, e.g., setting permissions
          # Ensure web server has appropriate permissions
          sudo chown -R www-data:www-data /var/www/html
        EOF
