name: Deploy to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no ./ ec2-user@YOUR_EC2_PUBLIC_IP:/var/www/html

    - name: SSH into EC2 and set up
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@YOUR_EC2_PUBLIC_IP << 'EOF'
          cd /var/www/html
          # Perform any setup tasks here, e.g., setting permissions
          # Ensure web server has appropriate permissions
          sudo chown -R www-data:www-data /var/www/html
        EOF
